version: '3.5'
services:
  redis:
    image: redis:4.0-alpine
  app:
    build:
      context: .
      dockerfile: ./.deploy/app/Dockerfile
    env_file: .env
    volumes:
      - .:/code
    environment:
      DJANGO_SETTINGS_MODULE: quantum_web.settings

    ports:
      - 8000:8000
    command: daphne -b 0.0.0.0 -p 8000 quantum_web.asgi:application
